// <auto-generated />
namespace DataBase_Scema_Test_Neo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class topics_questions_b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topics_questions_b));
        
        string IMigrationMetadata.Id
        {
            get { return "202301081118456_topics_questions_b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
